### ISSUE TITLE
Source for this dataset

### ISSUE THREAD

**Issue by chrzyki** [lexibank/starostinhmongmien#2]
What source should be cited for this dataset @LinguList?

Just the 'general' database?

```
@misc{Starostin2011,
    editor = {Starostin, George S. and Krylov, Phil},
    title = {The Global Lexicostatistical Database},
    url = {http://starling.rinet.ru/new100/main.htm},
    year = {2011}
}
```

**Comment by LinguList** [comment]
No misc, this is an incollection, of course (

@incollection{Starostin2011,
    author = {Starostin, George S.},
    title = { Annotated Swadesh wordlists for the Hmong group
(Hmong-Mien family).
},
    editor = {Starostin, George S. and Krylov, Phil},
    booktitle = {The Global Lexicostatistical Database},
    url =
{https://starling.rinet.ru/cgi-bin/bdescr.cgi?root=new100&morpho=0&basename=new100\hmo\hmo},
    year = {2011}, address = {Moscow}, publisher = {RGGU},
}

**Comment by chrzyki** [comment]
I was just pasting what currently is in `sources.bib`. Thanks for the update & citation.

**Comment by LinguList** [comment]
Please check here: https://starling.rinet.ru/new100/about.htm

George added citation information after I asked him, so let's follow
these guidelines.

**Comment by chrzyki** [comment]
Ah, perfect, thanks for the link!
